### ISSUE TITLE
Sorry I'm didn't know where I can text you either...

### ISSUE THREAD

**Issue by Elan-II** [truss-cpi/FFE-CHAdeMO#1]
Last half year I'm looking for way to start ford fusion/focus/c-max electric on board 3.3 kWt charger, but I'm have only charger, not entire car. I'm working on EV conversion and repair service, and would like to ask some of your can logs, become you somehow find that 0x7E2 asks charger some status. I can give you al information about other chargers, that I'm turn on instead, if needed this.

**Comment by Elan-II** [comment]
Because, not become...

**Comment by truss-cpi** [comment]
I did not write this code so I'm not sure what I can offer you.

The original author ran CANBus sniffs of the message traffic during normal operation and while it was connected to a Ford Diagnostic system.

**Comment by Elan-II** [comment]
Can you give me link where you get that original code?

**Comment by truss-cpi** [comment]
There is no original link. This was pursued as a personal project by the original author and the software was given to me when I purchased the hardware - as he did not wish to pursue development of it. I've posted it as open source so that others may use it. What you see IS the original code, with the exception of me cleaning up some formatting and adding more verbose comments.

There is other separate code I have not had a chance to look at that was used to control SOBDMs outside the vehicle, so they could be "stacked" together to act as a fast charger. There may be something of use in there. I'll try to get it posted to the main branch soon.

**Comment by truss-cpi** [comment]
[https://github.com/truss-cpi/FFE-CHAdeMO/blob/main/External_Charger/Module_Control/sodbm_controller.ino](https://github.com/truss-cpi/FFE-CHAdeMO/blob/main/External_Charger/Module_Control/sodbm_controller.ino) should have what you're looking for. It has several loops that simulate the output of frames the SOBDM expects to see on the bus.

**Comment by Elan-II** [comment]
As I'm see, it arduino project, can't you somehow add some strings like 
Serial.print (received CAN id);
Serial.print (received CAN data[i];
And make some logs for me, while car chargings. I can pay you for this.

**Comment by truss-cpi** [comment]
I can not. I am not a software developer and had not even looked at that code before I went looking for it yesterday.
